line-length = 99
indent-width = 4
target-version = "py39"

[lint]
preview = true
select = [
    "F",    # Pyflakes
    "E",    # pycodestyle
    "W",    # pycodestyle
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "COM",  # flake8-commas
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
    "ARG",  # flake8-unused-arguments
    "PTH",  # flake8-use-pathlib
    "PL",   # Pylint
    "RUF",  # Ruff-specific rules
]
ignore = [
    "bad-quotes-multiline-string",
    "builtin-open",
    "if-else-block-instead-of-if-exp",
    "collapsible-if",
    "multiple-with-statements",
    "if-else-block-instead-of-dict-get",
    "too-many-return-statements",
    "too-many-branches",
    "too-many-arguments",
    "too-many-statements",
    "too-many-statements-in-try-clause",
    "magic-value-comparison",
    "collapsible-else-if",
    "global-statement",
    "subprocess-run-without-check",
    "redefined-loop-name",
    "explicit-f-string-type-conversion",
    "mutable-class-default",
    "non-empty-init-module",
    "float-equality-comparison",
    "unused-noqa",
    "noqa-comments",

    # rules from preview
    "no-indented-block-comment",
    "missing-whitespace-around-arithmetic-operator",
    "missing-whitespace",
    "no-space-after-block-comment",
    "multiple-leading-hashes-for-block-comment",
    "too-many-public-methods",
    "too-many-positional-arguments",
    "literal-membership",
    "unspecified-encoding",
    "eq-without-hash",
]

[format]
indent-style = "space"
